# Generated by Django 2.2 on 2019-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Hats'), ('Te', 'Tees'), ('To', 'Tops')], default='', max_length=2),
        ),
    ]
