# Generated by Django 2.2 on 2019-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
